import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  CheckCircle, 
  TrendingUp, 
  Shield, 
  AlertTriangle,
  Star,
  FileText,
  Download,
  Share,
  Calendar
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export const ReviewCanvas = () => {
  const analysisMetrics = {
    overallConfidence: 92,
    totalFindings: 47,
    riskLevel: 'Low',
    recommendationScore: 8.4
  };

  const keyMetrics = [
    { label: 'Revenue Growth', value: '+45% YoY', status: 'positive' },
    { label: 'Gross Margin', value: '78%', status: 'positive' },
    { label: 'Cash Runway', value: '24 months', status: 'positive' },
    { label: 'Customer Concentration', value: '35% top 5', status: 'warning' }
  ];

  const citationSources = [
    { document: 'Loreal_Inventory_Manifest.xlsx', relevance: 95, pages: 'Sheet 1-3' },
    { document: 'Beauty_Market_Analysis.pdf', relevance: 88, pages: '4-7' },
    { document: 'Product_Pricing_Data.xlsx', relevance: 92, pages: 'Sheet 2' },
    { document: 'Competitor_Analysis.pdf', relevance: 76, pages: '12-25' }
  ];

  const agentContributions = [
    { agent: 'Dahlia: Demand Analysis', slides: 2, confidence: 94 },
    { agent: 'Fern: Financial Advisory', slides: 1, confidence: 89 },
    { agent: 'Sage: Sales Expert', slides: 1, confidence: 91 },
    { agent: 'Lily: Executive Summary', slides: 1, confidence: 96 }
  ];

  return (
    <div className="h-full p-6 space-y-6 institutional-scroll overflow-y-auto">
      {/* Header */}
      <div className="space-y-2">
        <h3 className="text-lg font-semibold institutional-heading">Slide Details</h3>
        <p className="text-sm text-muted-foreground">
          Analysis confidence and source attribution
        </p>
      </div>

      {/* Overall Analysis Score */}
      <Card className="p-4 bg-success/5 border-success/20">
        <div className="space-y-3">
          <div className="flex items-center space-x-2">
            <CheckCircle className="h-5 w-5 text-success" />
            <h4 className="font-medium text-success">Analysis Complete</h4>
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Overall Confidence</span>
              <span className="font-bold financial-data">{analysisMetrics.overallConfidence}%</span>
            </div>
            <Progress value={analysisMetrics.overallConfidence} className="h-2" />
          </div>
        </div>
      </Card>

      {/* Key Metrics */}
      <div className="space-y-4">
        <h4 className="font-medium text-muted-foreground uppercase tracking-wide text-sm">
          Key Metrics
        </h4>
        <div className="space-y-2">
          {keyMetrics.map((metric, index) => (
            <div key={index} className="flex items-center justify-between p-3 bg-card rounded border border-border-muted">
              <span className="text-sm text-muted-foreground">{metric.label}</span>
              <div className="flex items-center space-x-2">
                <span className="font-medium financial-data">{metric.value}</span>
                {metric.status === 'positive' ? (
                  <TrendingUp className="h-4 w-4 text-success" />
                ) : (
                  <AlertTriangle className="h-4 w-4 text-warning" />
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Source Citations */}
      <div className="space-y-4">
        <h4 className="font-medium text-muted-foreground uppercase tracking-wide text-sm">
          Source Citations
        </h4>
        <div className="space-y-2">
          {citationSources.map((source, index) => (
            <Card key={index} className="p-3">
              <div className="space-y-2">
                <div className="flex items-start justify-between">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{source.document}</p>
                    <p className="text-xs text-muted-foreground">Pages {source.pages}</p>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    {source.relevance}% relevance
                  </Badge>
                </div>
                <Progress value={source.relevance} className="h-1" />
              </div>
            </Card>
          ))}
        </div>
      </div>

      {/* Agent Contributions */}
      <div className="space-y-4">
        <h4 className="font-medium text-muted-foreground uppercase tracking-wide text-sm">
          Generated By
        </h4>
        <div className="space-y-2">
          {agentContributions.map((contribution, index) => (
            <div key={index} className="flex items-center justify-between p-3 bg-card rounded border border-border-muted">
              <div>
                <p className="text-sm font-medium">{contribution.agent}</p>
                <p className="text-xs text-muted-foreground">{contribution.slides} slide(s)</p>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-xs financial-data">{contribution.confidence}%</span>
                <div className="flex">
                  {Array.from({ length: 5 }).map((_, i) => (
                    <Star
                      key={i}
                      className={`h-3 w-3 ${
                        i < Math.floor(contribution.confidence / 20)
                          ? 'text-warning fill-current'
                          : 'text-muted'
                      }`}
                    />
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Risk Assessment */}
      <Card className="p-4 bg-warning/5 border-warning/20">
        <div className="space-y-3">
          <div className="flex items-center space-x-2">
            <Shield className="h-4 w-4 text-warning" />
            <h5 className="font-medium text-warning">Risk Assessment</h5>
          </div>
          <div className="text-sm text-muted-foreground space-y-2">
            <div className="flex items-center justify-between">
              <span>Overall Risk Level</span>
              <Badge variant="outline" className="text-warning border-warning">
                {analysisMetrics.riskLevel}
              </Badge>
            </div>
            <div className="text-xs space-y-1">
              <p>• Product demand: Strong</p>
              <p>• Market position: Premium brand</p>
              <p>• Recovery potential: High</p>
              <p>• Liquidation risks: Manageable</p>
            </div>
          </div>
        </div>
      </Card>

      {/* Recommendation Score */}
      <Card className="p-4 bg-accent-blue/5 border-accent-blue/20">
        <div className="space-y-3">
          <div className="flex items-center space-x-2">
            <Star className="h-4 w-4 text-accent-blue" />
            <h5 className="font-medium text-accent-blue">Investment Score</h5>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold financial-data text-accent-blue">
              {analysisMetrics.recommendationScore}/10
            </p>
            <p className="text-sm text-muted-foreground">Strong Buy Recommendation</p>
          </div>
        </div>
      </Card>

      {/* Quick Actions */}
      <div className="space-y-4">
        <h4 className="font-medium text-muted-foreground uppercase tracking-wide text-sm">
          Quick Actions
        </h4>
        <div className="space-y-2">
          <Button variant="outline" size="sm" className="w-full justify-start surgical-button">
            <Download className="h-4 w-4 mr-2" />
            Export Analysis
          </Button>
          <Button variant="outline" size="sm" className="w-full justify-start surgical-button">
            <Share className="h-4 w-4 mr-2" />
            Share with Team
          </Button>
          <Button variant="outline" size="sm" className="w-full justify-start surgical-button">
            <Calendar className="h-4 w-4 mr-2" />
            Schedule Review
          </Button>
          <Button variant="outline" size="sm" className="w-full justify-start surgical-button">
            <FileText className="h-4 w-4 mr-2" />
            Generate Report
          </Button>
        </div>
      </div>
    </div>
  );
};